[tools]
bun = "latest"
elixir = "1.19"
erlang = "28"
go = "latest"
golangci-lint = "latest"
neovim = "latest"
node = "latest"
pipx = "latest"
"pipx:gamdl" = "latest"
"pipx:sqlit-tui" = "latest"
pnpm = "latest"
python = "latest"
"ubi:sst/opencode" = "1.0.134"
usage = "latest"
usql = "latest"
