[tools]
bun = "latest"
go = "latest"
golangci-lint = "latest"
neovim = "latest"
node = "latest"
pipx = "latest"
"pipx:gamdl" = "latest"
"pipx:sqlit-tui" = "latest"
python = "latest"
ruby = "4"
"ubi:sst/opencode" = "1.0.134"
usage = "latest"
